### ISSUE TITLE
Secondary Unit Types / Numbers are dropped

### ISSUE THREAD

**Issue by shanonvl** [cayasso/smartystreets-api#4]
First off, thanks for this.    

I found a bug with apartment/suite numbers being dropped from the query.  I checked out and verified that [the parse-address library supports them](https://github.com/hassansin/parse-address/blob/master/test.js#L181-L182). 

It looks like they need to be added to the `street` | `street2` | `secondary` property ( not sure which one is best ) in your [normalize function](https://github.com/cayasso/smartystreets-api/blob/master/lib/utils.js#L34-L40).

Example input:  `550 S 400 E #3206, Salt Lake City UT 84111` 

The `#3206` is dropped.

**Comment by cayasso** [comment]
@shanonvl Can you please double check if this commit is working correctly for you https://github.com/cayasso/smartystreets-api/commit/13ed1610be2e02c565d8c0b965446c756b4777f5 It should add sec units. Let me know so I can release.

**Comment by shanonvl** [comment]
Added a comment to the commit: https://github.com/cayasso/smartystreets-api/commit/13ed1610be2e02c565d8c0b965446c756b4777f5#commitcomment-27978341

Working correctly for me.   Thanks again!
